# Project: Sistem-Perpustakaan-SLL
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o linked.o queue.o stack.o perpustakaan.o
LINKOBJ  = main.o linked.o queue.o stack.o perpustakaan.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Sistem-Perpustakaan-SLL.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

linked.o: linked.c
	$(CC) -c linked.c -o linked.o $(CFLAGS)

queue.o: queue.c
	$(CC) -c queue.c -o queue.o $(CFLAGS)

stack.o: stack.c
	$(CC) -c stack.c -o stack.o $(CFLAGS)

perpustakaan.o: perpustakaan.c
	$(CC) -c perpustakaan.c -o perpustakaan.o $(CFLAGS)
